-- ===========================================================================
-- 40-grants.sql — least privilege for the two non-superuser roles.
--
-- Requires :wh_user and :rls_user. Idempotent. Uses \gexec for the same reason
-- 20-schemas-roles.sql does: psql does not interpolate :vars inside a
-- dollar-quoted block.
--
-- The shape of this file is the whole access argument for the warehouse:
--
--   warehouse       owns raw / staging / marts / warehouse / snapshots. It is
--                   the only identity that can write anything.
--   warehouse_rls   can SELECT from marts and from the operational metadata
--                   the dashboard needs, and can APPEND (only) to the access
--                   audit through a SECURITY DEFINER function. It has no
--                   access to `raw` or `staging` at all.
--
-- WHY warehouse_rls IS LOCKED OUT OF `raw`. Everything in raw is already
-- masked — it has to be; anti-pattern §7.5 forbids unmasked personal data
-- landing even transiently. So this is not the containment boundary for
-- personal data. It is the containment boundary for TENANT data: `raw` is
-- append-only and carries no RLS, because RLS on a landing zone would fight
-- the loader on every insert. Granting the dashboard's identity SELECT there
-- would hand it an un-policied copy of every tenant's rows and make every RLS
-- policy on marts a formality.
-- ===========================================================================

-- --- The owning role -------------------------------------------------------
SELECT format('GRANT USAGE, CREATE ON SCHEMA raw, staging, marts, warehouse, snapshots TO %I', :'wh_user') \gexec
SELECT format('GRANT USAGE ON SCHEMA public TO %I', :'wh_user') \gexec

-- --- The read-only, RLS-constrained role -----------------------------------
-- USAGE on marts and warehouse only. No raw. No staging. No snapshots.
SELECT format('GRANT USAGE ON SCHEMA marts, warehouse TO %I', :'rls_user') \gexec
SELECT format('GRANT SELECT ON ALL TABLES IN SCHEMA marts TO %I', :'rls_user') \gexec

-- Operational metadata the semantic-api and the exporter genuinely need,
-- enumerated one by one rather than granted schema-wide, so a future table in
-- `warehouse` is invisible until somebody decides it should not be.
SELECT format('GRANT SELECT ON warehouse.%I TO %I', t, :'rls_user')
FROM unnest(ARRAY['pipeline_state','mart_sla','mart_freshness','tenant_registry',
                  'dbt_run_result','column_policy']) AS t
\gexec

-- Append-only audit. No INSERT on the table itself: the SECURITY DEFINER
-- function is the only write path, so the read identity cannot craft an audit
-- row that disagrees with its own session, and cannot delete one.
SELECT format('REVOKE ALL ON warehouse.access_audit FROM %I', :'rls_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION warehouse.log_access(text,text,text,bigint,text,jsonb) TO %I',
              :'rls_user') \gexec

-- --- The CDC loader identity (Backend's process) ---------------------------
--
-- The narrowest set that lets contract 05's loader do its job:
--   * USAGE on raw and warehouse (no marts, no staging, no snapshots)
--   * INSERT + SELECT on raw.* -- SELECT so it can resume from max(_lsn);
--     no UPDATE and no DELETE, because the landing zone is APPEND-ONLY and a
--     tombstone is a new row, never an in-place change. That rule is now
--     enforced by the grant rather than trusted to the loader.
--   * SELECT on warehouse.column_policy -- it reads the policy, never writes one.
--   * full DML on warehouse.pipeline_state -- it is the writer of record.
--   * NO CREATE anywhere. raw.* DDL is generated by DWH from the policy
--     (make warehouse-raw-ddl). A loader that could CREATE its own landing
--     table could land a column with no policy row, and "unclassified is a
--     hard failure" would become a convention instead of a structural fact.
SELECT format('GRANT USAGE ON SCHEMA raw, warehouse TO %I', :'loader_user') \gexec
SELECT format('GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA raw TO %I', :'loader_user') \gexec
SELECT format('GRANT SELECT ON warehouse.column_policy TO %I', :'loader_user') \gexec
SELECT format('GRANT SELECT ON warehouse.tenant_registry TO %I', :'loader_user') \gexec
SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON warehouse.pipeline_state TO %I', :'loader_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION warehouse.log_access(text,text,text,bigint,text,jsonb) TO %I',
              :'loader_user') \gexec
SELECT format('REVOKE CREATE ON SCHEMA raw, warehouse FROM %I', :'loader_user') \gexec

-- --- Default privileges ----------------------------------------------------
-- Cover tables dbt has not created yet. Without this, every new mart model is
-- invisible to the dashboard until somebody remembers to re-run a grant —
-- which presents as "the metric returns nothing" and gets diagnosed as a data
-- problem. FOR ROLE warehouse, because default privileges attach to the
-- CREATING role and dbt creates as warehouse.
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA marts GRANT SELECT ON TABLES TO %I',
              :'wh_user', :'rls_user') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA marts GRANT SELECT ON SEQUENCES TO %I',
              :'wh_user', :'rls_user') \gexec
-- Same reasoning for the loader and the landing zone: a raw table generated
-- tomorrow must be writable by the loader without a manual grant, or the
-- pipeline stops with a permissions error that reads like a schema bug.
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA raw GRANT SELECT, INSERT ON TABLES TO %I',
              :'wh_user', :'loader_user') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA raw GRANT USAGE, SELECT ON SEQUENCES TO %I',
              :'wh_user', :'loader_user') \gexec

-- --- Explicit denials ------------------------------------------------------
-- Belt and braces, but they cost nothing and they are what a reviewer greps for.
SELECT format('REVOKE ALL ON SCHEMA raw, staging, snapshots FROM %I', :'rls_user') \gexec
SELECT format('REVOKE ALL ON SCHEMA marts, staging, snapshots FROM %I', :'loader_user') \gexec
SELECT format('REVOKE CREATE ON SCHEMA marts, warehouse FROM %I', :'rls_user') \gexec

REVOKE ALL ON SCHEMA raw, staging, snapshots FROM PUBLIC;
